# Generated by Django 5.0.7 on 2024-07-23 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 23, 13, 27, 15, 746440, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
